### ISSUE TITLE
Install instructions don't work

### ISSUE THREAD

**Issue by uecasm** [protocolbuffers/protoscope#20]
```
$ go version
go version go1.15.15 linux/amd64
$ go install github.com/protocolbuffers/protoscope/cmd/protoscope...@latest
go: warning: "github.com/protocolbuffers/protoscope/cmd/protoscope...@latest" matched no packages
```

**Comment by perezd** [comment]
I recommend upgrading your version of go and trying again. Can't repro:

![Screenshot 2023-07-05 at 10 06 52 AM](https://github.com/protocolbuffers/protoscope/assets/20598/09bdb91c-eea8-4dd1-a1e2-54100b2e85df)

**Comment by uecasm** [comment]
I'm using the version included with Debian 11.

It would be nice if the install instructions either specified a minimum version requirement or instructions that worked with older versions as well.

**Comment by perezd** [comment]
@uecasm That's a fairly old release...they're out with 1.20 now, and per their [release policy](https://go.dev/doc/devel/release#policy):

    Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release. 

I'd suggest updating Go *especially* because it's the default in Debian, they tend to be fairly conservative/slow when it comes to upgrades, but that does not imply it's well supported by any particular project or ecosystem. That's their tradeoff they're making.
